# Board settings.
BOARD_TAG = uno
MONITOR_PORT = /dev/ttyACM0

# Which header files and libraries to use
LIBS = SoftwareSerial SPI

include $(HOME)/.vim/bundle/vim-arduino/Makefile/arduino-mk/Arduino.mk
